DEMO_JOBS = [
    {
        "title": "Python Developer",
        "company": "TechNova Solutions",
        "location": "Hyderabad",
        "source": "demo",
        "job_url": "https://demo.jobspy.local/jobs/python-developer-hyderabad",
        "description": "Entry-level Python developer role working on backend APIs and data scripts.",
        "experience_level": "Fresher",
        "employment_type": "Full-time",
    },
    {
        "title": "Data Analyst",
        "company": "Insight Analytics",
        "location": "Remote",
        "source": "demo",
        "job_url": "https://demo.jobspy.local/jobs/data-analyst-remote",
        "description": "Analyze business data, build dashboards, and support reporting for stakeholders.",
        "experience_level": "Fresher",
        "employment_type": "Full-time",
    },
    {
        "title": "SQL Developer",
        "company": "DataCore Systems",
        "location": "Bengaluru",
        "source": "demo",
        "job_url": "https://demo.jobspy.local/jobs/sql-developer-bengaluru",
        "description": "Write and optimize SQL queries, maintain databases, and support ETL pipelines.",
        "experience_level": "0-2 years",
        "employment_type": "Full-time",
    },
    {
        "title": "Power BI Analyst",
        "company": "BrightMetrics",
        "location": "Hyderabad",
        "source": "demo",
        "job_url": "https://demo.jobspy.local/jobs/power-bi-analyst-hyderabad",
        "description": "Build Power BI dashboards and reports for operations and finance teams.",
        "experience_level": "1-3 years",
        "employment_type": "Full-time",
    },
    {
        "title": "Data Engineer",
        "company": "CloudStream Tech",
        "location": "Remote",
        "source": "demo",
        "job_url": "https://demo.jobspy.local/jobs/data-engineer-remote",
        "description": "Design data pipelines, work with cloud warehouses, and support analytics platforms.",
        "experience_level": "2-4 years",
        "employment_type": "Full-time",
    },
]

DEMO_ALERT_RULES = [
    {
        "alert_name": "Python Fresher Jobs",
        "recipient_name": "Arjun",
        "recipient_email": "arjun@example.com",
        "keywords": "Python",
        "location": "Hyderabad",
        "experience_level": "Fresher",
        "employment_type": None,
        "is_active": True,
    },
    {
        "alert_name": "Data Analyst Remote Jobs",
        "recipient_name": "Priya",
        "recipient_email": "priya@example.com",
        "keywords": "Data Analyst",
        "location": "Remote",
        "experience_level": "Fresher",
        "employment_type": None,
        "is_active": True,
    },
    {
        "alert_name": "SQL Developer Jobs",
        "recipient_name": "Rahul",
        "recipient_email": "rahul@example.com",
        "keywords": "SQL",
        "location": "",
        "experience_level": None,
        "employment_type": None,
        "is_active": True,
    },
]
